<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLiDiemSV" Class="QLDDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DUCDU\SQLEXPRESS;Initial Catalog=QuanLiDiemSV;Integrated Security=True" SettingsObjectName="Quanlidiemsinhvien.Properties.Settings" SettingsPropertyName="QuanLiDiemSVConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.HeDT" Member="HeDTs">
    <Type Name="HeDT">
      <Column Name="MaHeDT" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenHeDT" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Association Name="HeDT_Lop" Member="Lops" ThisKey="MaHeDT" OtherKey="MaHeDT" Type="Lop" />
    </Type>
  </Table>
  <Table Name="dbo.Khoa" Member="Khoas">
    <Type Name="Khoa">
      <Column Name="MaKhoa" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKhoa" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Khoa_Lop" Member="Lops" ThisKey="MaKhoa" OtherKey="MaKhoa" Type="Lop" />
      <Association Name="Khoa_MonHoc" Member="MonHocs" ThisKey="MaKhoa" OtherKey="MaKhoa" Type="MonHoc" />
      <Association Name="Khoa_SinhVien" Member="SinhViens" ThisKey="MaKhoa" OtherKey="MaKhoa" Type="SinhVien" />
    </Type>
  </Table>
  <Table Name="dbo.KhoaHoc" Member="KhoaHocs">
    <Type Name="KhoaHoc">
      <Column Name="MaKhoaHoc" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKhoaHoc" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="KhoaHoc_Lop" Member="Lops" ThisKey="MaKhoaHoc" OtherKey="MaKhoaHoc" Type="Lop" />
    </Type>
  </Table>
  <Table Name="dbo.Lop" Member="Lops">
    <Type Name="Lop">
      <Column Name="MaLop" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="MaKhoa" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MaHeDT" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MaKhoaHoc" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Association Name="Lop_SinhVien" Member="SinhViens" ThisKey="MaLop" OtherKey="MaLop" Type="SinhVien" />
      <Association Name="HeDT_Lop" Member="HeDT" ThisKey="MaHeDT" OtherKey="MaHeDT" Type="HeDT" IsForeignKey="true" />
      <Association Name="Khoa_Lop" Member="Khoa" ThisKey="MaKhoa" OtherKey="MaKhoa" Type="Khoa" IsForeignKey="true" />
      <Association Name="KhoaHoc_Lop" Member="KhoaHoc" ThisKey="MaKhoaHoc" OtherKey="MaKhoaHoc" Type="KhoaHoc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HocKy" Member="HocKies">
    <Type Name="HocKy">
      <Column Name="MaHK" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenHK" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="HocKy_MonHoc" Member="MonHocs" ThisKey="MaHK" OtherKey="MaHK" Type="MonHoc" />
    </Type>
  </Table>
  <Table Name="dbo.ThongTin" Member="ThongTins">
    <Type Name="ThongTin">
      <Column Name="Tinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DonViChuQuan" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TenTruong" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="KhoaHoc" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NganhHoc" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ChuyenNganh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MonHoc" Member="MonHocs">
    <Type Name="MonHoc">
      <Column Name="MaMH" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenMH" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="SoTC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaHK" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="MaKhoa" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Association Name="MonHoc_DiemHP" Member="DiemHPs" ThisKey="MaMH" OtherKey="MaMH" Type="DiemHP" />
      <Association Name="HocKy_MonHoc" Member="HocKy" ThisKey="MaHK" OtherKey="MaHK" Type="HocKy" IsForeignKey="true" />
      <Association Name="Khoa_MonHoc" Member="Khoa" ThisKey="MaKhoa" OtherKey="MaKhoa" Type="Khoa" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SinhVien" Member="SinhViens">
    <Type Name="SinhVien">
      <Column Name="MaSV" Type="System.String" DbType="Char(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenSV" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="QueQuan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaLop" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="MaKhoa" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Association Name="SinhVien_DiemHP" Member="DiemHPs" ThisKey="MaSV" OtherKey="MaSV" Type="DiemHP" />
      <Association Name="Khoa_SinhVien" Member="Khoa" ThisKey="MaKhoa" OtherKey="MaKhoa" Type="Khoa" IsForeignKey="true" />
      <Association Name="Lop_SinhVien" Member="Lop" ThisKey="MaLop" OtherKey="MaLop" Type="Lop" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DiemHP" Member="DiemHPs">
    <Type Name="DiemHP">
      <Column Name="MaSV" Type="System.String" DbType="Char(15)" CanBeNull="true" />
      <Column Name="MaMH" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="DiemKT1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DiemKT2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Diemthi" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="MonHoc_DiemHP" Member="MonHoc" ThisKey="MaMH" OtherKey="MaMH" Type="MonHoc" IsForeignKey="true" />
      <Association Name="SinhVien_DiemHP" Member="SinhVien" ThisKey="MaSV" OtherKey="MaSV" Type="SinhVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Taikhoan" Member="Taikhoans">
    <Type Name="Taikhoan">
      <Column Name="id_user" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="passwd" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaCB" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HotenCB" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DiachiCB" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Taikhoan_Phanquyen" Member="Phanquyens" ThisKey="id_user" OtherKey="id_user" Type="Phanquyen" />
    </Type>
  </Table>
  <Table Name="dbo.Phanquyen" Member="Phanquyens">
    <Type Name="Phanquyen">
      <Column Name="id_per" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_user" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Al" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Ad" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Edit" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Del" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Taikhoan_Phanquyen" Member="Taikhoan" ThisKey="id_user" OtherKey="id_user" Type="Taikhoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.Lop_SelectAll" Method="Lop_SelectAll">
    <ElementType Name="Lop_SelectAllResult">
      <Column Name="MaLop" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="MaKhoa" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MaHeDT" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MaKhoaHoc" Type="System.String" DbType="Char(5)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DanhsachdiemSV" Method="DanhsachdiemSV">
    <ElementType Name="DanhsachdiemSVResult">
      <Column Name="MaSV" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="TenSV" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MaMH" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="TenMH" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="SoTC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HocKy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Lanhoc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Lanthi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Danhgia" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="DiemKT1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DiemKT2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ThiketthucHP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TongketHP" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Diemchu" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Lop_Insert" Method="Lop_Insert">
    <Parameter Name="MaLop" Parameter="maLop" Type="System.String" DbType="Char(5)" />
    <Parameter Name="TenLop" Parameter="tenLop" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Makhoa" Parameter="makhoa" Type="System.String" DbType="Char(5)" />
    <Parameter Name="MaHeDT" Parameter="maHeDT" Type="System.String" DbType="Char(5)" />
    <Parameter Name="MaKhoaHoc" Parameter="maKhoaHoc" Type="System.String" DbType="Char(5)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Lop_Update" Method="Lop_Update">
    <Parameter Name="MaLop" Parameter="maLop" Type="System.String" DbType="Char(5)" />
    <Parameter Name="TenLop" Parameter="tenLop" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="Makhoa" Parameter="makhoa" Type="System.String" DbType="Char(5)" />
    <Parameter Name="MaHeDT" Parameter="maHeDT" Type="System.String" DbType="Char(5)" />
    <Parameter Name="MaKhoaHoc" Parameter="maKhoaHoc" Type="System.String" DbType="Char(5)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Lop_Delete" Method="Lop_Delete">
    <Parameter Name="MaLop" Parameter="maLop" Type="System.String" DbType="Char(5)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SinhVien_Delete" Method="SinhVien_Delete">
    <Parameter Name="MaSV" Parameter="maSV" Type="System.String" DbType="Char(15)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SinhVien_Search" Method="SinhVien_Search">
    <Parameter Name="TenSV" Parameter="tenSV" Type="System.String" DbType="NVarChar(20)" />
    <ElementType Name="SinhVien_SearchResult">
      <Column Name="MaSV" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="TenSV" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="QueQuan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaLop" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.HocKy_Insert" Method="HocKy_Insert">
    <Parameter Name="MaHK" Parameter="maHK" Type="System.String" DbType="Char(10)" />
    <Parameter Name="TenHK" Parameter="tenHK" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.HocKy_SelectAll" Method="HocKy_SelectAll">
    <ElementType Name="HocKy_SelectAllResult">
      <Column Name="MaHK" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="TenHK" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.HocKy_Update" Method="HocKy_Update">
    <Parameter Name="MaHK" Parameter="maHK" Type="System.String" DbType="Char(10)" />
    <Parameter Name="TenHK" Parameter="tenHK" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.HocKy_Delete" Method="HocKy_Delete">
    <Parameter Name="MaHK" Parameter="maHK" Type="System.String" DbType="Char(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.MonHP_Delete" Method="MonHP_Delete">
    <Parameter Name="MaMH" Parameter="maMH" Type="System.String" DbType="Char(5)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SinhVien_SelectAll" Method="SinhVien_SelectAll">
    <ElementType Name="SinhVien_SelectAllResult">
      <Column Name="MaSV" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="TenSV" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="QueQuan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaLop" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ThongTin_SelecAll" Method="ThongTin_SelecAll">
    <ElementType Name="ThongTin_SelecAllResult">
      <Column Name="Tinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DonViChuQuan" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TenTruong" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="KhoaHoc" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NganhHoc" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ChuyenNganh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ThongTin_Update" Method="ThongTin_Update">
    <Parameter Name="Tinh" Parameter="tinh" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="DonViChuQuan" Parameter="donViChuQuan" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="TenTruong" Parameter="tenTruong" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="KhoaHoc" Parameter="khoaHoc" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="NganhHoc" Parameter="nganhHoc" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="ChuyenNganh" Parameter="chuyenNganh" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SinhVien_SelectMaSV" Method="SinhVien_SelectMaSV">
    <Parameter Name="MaSV" Parameter="maSV" Type="System.String" DbType="Char(15)" />
    <ElementType Name="SinhVien_SelectMaSVResult">
      <Column Name="MaSV" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="TenSV" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="QueQuan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaLop" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Khoa_SelectAll" Method="Khoa_SelectAll">
    <ElementType Name="Khoa_SelectAllResult">
      <Column Name="MaKhoa" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="TenKhoa" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Khoa_Insert" Method="Khoa_Insert">
    <Parameter Name="MaKhoa" Parameter="maKhoa" Type="System.String" DbType="Char(5)" />
    <Parameter Name="TenKhoa" Parameter="tenKhoa" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="DiaChi" Parameter="diaChi" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="DienThoai" Parameter="dienThoai" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Khoa_Delete" Method="Khoa_Delete">
    <Parameter Name="MaKhoa" Parameter="maKhoa" Type="System.String" DbType="Char(5)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.HocKy_Update" Method="HocKy_Update1">
    <Parameter Name="MaHK" Parameter="maHK" Type="System.String" DbType="Char(10)" />
    <Parameter Name="TenHK" Parameter="tenHK" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Khoa_Update" Method="Khoa_Update">
    <Parameter Name="MaKhoa" Parameter="maKhoa" Type="System.String" DbType="Char(5)" />
    <Parameter Name="TenKhoa" Parameter="tenKhoa" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="DiaChi" Parameter="diaChi" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="DienThoai" Parameter="dienThoai" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Khoa_Delete" Method="Khoa_Delete1">
    <Parameter Name="MaKhoa" Parameter="maKhoa" Type="System.String" DbType="Char(5)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.KhoaHoc_Delete" Method="KhoaHoc_Delete">
    <Parameter Name="MaKhoaHoc" Parameter="maKhoaHoc" Type="System.String" DbType="Char(5)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.KhoaHoc_Insert" Method="KhoaHoc_Insert">
    <Parameter Name="MaKhoaHoc" Parameter="maKhoaHoc" Type="System.String" DbType="Char(5)" />
    <Parameter Name="TenKhoaHoc" Parameter="tenKhoaHoc" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.KhoaHoc_SelectAll" Method="KhoaHoc_SelectAll">
    <ElementType Name="KhoaHoc_SelectAllResult">
      <Column Name="MaKhoaHoc" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="TenKhoaHoc" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.KhoaHoc_Update" Method="KhoaHoc_Update">
    <Parameter Name="MaKhoaHoc" Parameter="maKhoaHoc" Type="System.String" DbType="Char(5)" />
    <Parameter Name="TenKhoaHoc" Parameter="tenKhoaHoc" Type="System.String" DbType="NVarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.HeDT_Delete" Method="HeDT_Delete">
    <Parameter Name="MaHeDT" Parameter="maHeDT" Type="System.String" DbType="Char(5)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.HeDT_Insert" Method="HeDT_Insert">
    <Parameter Name="MaHeDT" Parameter="maHeDT" Type="System.String" DbType="Char(5)" />
    <Parameter Name="TenHeDT" Parameter="tenHeDT" Type="System.String" DbType="NVarChar(40)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.HeDT_Update" Method="HeDT_Update">
    <Parameter Name="MaHeDT" Parameter="maHeDT" Type="System.String" DbType="Char(5)" />
    <Parameter Name="TenHeDT" Parameter="tenHeDT" Type="System.String" DbType="NVarChar(40)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.HocKy_Delete" Method="HocKy_Delete1">
    <Parameter Name="MaHK" Parameter="maHK" Type="System.String" DbType="Char(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.HeDT_SelectAll" Method="HeDT_SelectAll">
    <ElementType Name="HeDT_SelectAllResult">
      <Column Name="MaHeDT" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="TenHeDT" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Lop_SelectMaHeDT" Method="Lop_SelectMaHeDT">
    <Parameter Name="MaHeDT" Parameter="maHeDT" Type="System.String" DbType="Char(5)" />
    <ElementType Name="Lop_SelectMaHeDTResult">
      <Column Name="MaLop" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="MaKhoa" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MaHeDT" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MaKhoaHoc" Type="System.String" DbType="Char(5)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Lop_SelectMaKhoa" Method="Lop_SelectMaKhoa">
    <Parameter Name="MaKhoa" Parameter="maKhoa" Type="System.String" DbType="Char(5)" />
    <ElementType Name="Lop_SelectMaKhoaResult">
      <Column Name="MaLop" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="MaKhoa" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MaHeDT" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MaKhoaHoc" Type="System.String" DbType="Char(5)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Lop_SelectMaKhoaHoc" Method="Lop_SelectMaKhoaHoc">
    <Parameter Name="MaKhoaHoc" Parameter="maKhoaHoc" Type="System.String" DbType="Char(5)" />
    <ElementType Name="Lop_SelectMaKhoaHocResult">
      <Column Name="MaLop" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="MaKhoa" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MaHeDT" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MaKhoaHoc" Type="System.String" DbType="Char(5)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.MonHP_SelectMaKhoa" Method="MonHP_SelectMaKhoa">
    <Parameter Name="MaKhoa" Parameter="maKhoa" Type="System.String" DbType="Char(5)" />
    <ElementType Name="MonHP_SelectMaKhoaResult">
      <Column Name="MaMH" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="TenMH" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="SoTC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaHK" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="MaKhoa" Type="System.String" DbType="Char(5)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.MonHP_Insert" Method="MonHP_Insert">
    <Parameter Name="MaMH" Parameter="maMH" Type="System.String" DbType="Char(5)" />
    <Parameter Name="TenMH" Parameter="tenMH" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="SoTC" Parameter="soTC" Type="System.Int32" DbType="Int" />
    <Parameter Name="MaHK" Parameter="maHK" Type="System.String" DbType="Char(10)" />
    <Parameter Name="MaKhoa" Parameter="maKhoa" Type="System.String" DbType="Char(5)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.MonHP_Update" Method="MonHP_Update">
    <Parameter Name="MaMH" Parameter="maMH" Type="System.String" DbType="Char(5)" />
    <Parameter Name="TenMH" Parameter="tenMH" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="SoTC" Parameter="soTC" Type="System.Int32" DbType="Int" />
    <Parameter Name="MaHK" Parameter="maHK" Type="System.String" DbType="Char(10)" />
    <Parameter Name="MaKhoa" Parameter="maKhoa" Type="System.String" DbType="Char(5)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.MonHP_SelectMK" Method="MonHP_SelectMK">
    <ElementType Name="MonHP_SelectMKResult">
      <Column Name="MaKhoa" Type="System.String" DbType="Char(5)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.MonHP_SelectAll" Method="MonHP_SelectAll">
    <ElementType Name="MonHP_SelectAllResult">
      <Column Name="MaMH" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="TenMH" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="SoTC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaHK" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="MaKhoa" Type="System.String" DbType="Char(5)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Khoahoc_SelectKH" Method="Khoahoc_SelectKH">
    <ElementType Name="Khoahoc_SelectKHResult">
      <Column Name="MaKhoaHoc" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.HeDT_SelectMHDT" Method="HeDT_SelectMHDT">
    <ElementType Name="HeDT_SelectMHDTResult">
      <Column Name="MaHeDT" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Lop_SelectMK" Method="Lop_SelectMK">
    <ElementType Name="Lop_SelectMKResult">
      <Column Name="MaKhoa" Type="System.String" DbType="Char(5)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SinhVien_SelectMK" Method="SinhVien_SelectMK">
    <ElementType Name="SinhVien_SelectMKResult">
      <Column Name="MaKhoa" Type="System.String" DbType="Char(5)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SinhVien_SelectML" Method="SinhVien_SelectML">
    <ElementType Name="SinhVien_SelectMLResult">
      <Column Name="MaLop" Type="System.String" DbType="Char(5)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SinhVien_SelectMaKhoa" Method="SinhVien_SelectMaKhoa">
    <Parameter Name="MaKhoa" Parameter="maKhoa" Type="System.String" DbType="Char(5)" />
    <ElementType Name="SinhVien_SelectMaKhoaResult">
      <Column Name="MaSV" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="TenSV" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="QueQuan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaLop" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="MaKhoa" Type="System.String" DbType="Char(5)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SinhVien_Insert" Method="SinhVien_Insert">
    <Parameter Name="MaSV" Parameter="maSV" Type="System.String" DbType="Char(15)" />
    <Parameter Name="TenSV" Parameter="tenSV" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="NgaySinh" Parameter="ngaySinh" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="QueQuan" Parameter="queQuan" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="MaLop" Parameter="maLop" Type="System.String" DbType="Char(5)" />
    <Parameter Name="GioiTinh" Parameter="gioiTinh" Type="System.String" DbType="NVarChar(5)" />
    <Parameter Name="MaKhoa" Parameter="maKhoa" Type="System.String" DbType="Char(5)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SinhVien_SelectMaLop" Method="SinhVien_SelectMaLop">
    <Parameter Name="MaLop" Parameter="maLop" Type="System.String" DbType="Char(5)" />
    <ElementType Name="SinhVien_SelectMaLopResult">
      <Column Name="MaSV" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="TenSV" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="QueQuan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaLop" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="MaKhoa" Type="System.String" DbType="Char(5)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DiemHP_Delete" Method="DiemHP_Delete">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Diem_HPSelectAll" Method="Diem_HPSelectAll">
    <ElementType Name="Diem_HPSelectAllResult">
      <Column Name="MaSV" Type="System.String" DbType="Char(15)" CanBeNull="true" />
      <Column Name="MaMH" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MaLop" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MaHK" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="DiemKT1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DiemKT2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Diemthi" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Diem_HPSelectHK" Method="Diem_HPSelectHK">
    <Parameter Name="MaHK" Parameter="maHK" Type="System.String" DbType="Char(10)" />
    <ElementType Name="Diem_HPSelectHKResult">
      <Column Name="MaSV" Type="System.String" DbType="Char(15)" CanBeNull="true" />
      <Column Name="MaMH" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MaLop" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MaHK" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="DiemKT1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DiemKT2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Diemthi" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Diem_HPSelectMH" Method="Diem_HPSelectMH">
    <Parameter Name="MaMH" Parameter="maMH" Type="System.String" DbType="Char(5)" />
    <ElementType Name="Diem_HPSelectMHResult">
      <Column Name="MaSV" Type="System.String" DbType="Char(15)" CanBeNull="true" />
      <Column Name="MaMH" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MaLop" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MaHK" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="DiemKT1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DiemKT2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Diemthi" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Diem_HPSelectML" Method="Diem_HPSelectML">
    <Parameter Name="MaLop" Parameter="maLop" Type="System.String" DbType="Char(5)" />
    <ElementType Name="Diem_HPSelectMLResult">
      <Column Name="MaSV" Type="System.String" DbType="Char(15)" CanBeNull="true" />
      <Column Name="MaMH" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MaLop" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MaHK" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="DiemKT1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DiemKT2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Diemthi" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Diem_HPSelectSV" Method="Diem_HPSelectSV">
    <Parameter Name="MaSV" Parameter="maSV" Type="System.String" DbType="Char(15)" />
    <ElementType Name="Diem_HPSelectSVResult">
      <Column Name="MaSV" Type="System.String" DbType="Char(15)" CanBeNull="true" />
      <Column Name="MaMH" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MaLop" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MaHK" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="DiemKT1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DiemKT2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Diemthi" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.DiemHP_MaHK" Method="DiemHP_MaHK">
    <ElementType Name="DiemHP_MaHKResult">
      <Column Name="MaHK" Type="System.String" DbType="Char(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DiemHP_MaLop" Method="DiemHP_MaLop">
    <ElementType Name="DiemHP_MaLopResult">
      <Column Name="MaLop" Type="System.String" DbType="Char(5)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DiemHP_MaMH" Method="DiemHP_MaMH">
    <ElementType Name="DiemHP_MaMHResult">
      <Column Name="MaMH" Type="System.String" DbType="Char(5)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DiemHP_MaSV" Method="DiemHP_MaSV">
    <ElementType Name="DiemHP_MaSVResult">
      <Column Name="MaSV" Type="System.String" DbType="Char(15)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SinhVien_Update" Method="SinhVien_Update">
    <Parameter Name="MaSV" Parameter="maSV" Type="System.String" DbType="Char(15)" />
    <Parameter Name="TenSV" Parameter="tenSV" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="NgaySinh" Parameter="ngaySinh" Type="System.DateTime" DbType="Date" />
    <Parameter Name="QueQuan" Parameter="queQuan" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="MaLop" Parameter="maLop" Type="System.String" DbType="Char(5)" />
    <Parameter Name="GioiTinh" Parameter="gioiTinh" Type="System.String" DbType="NVarChar(5)" />
    <Parameter Name="MaKhoa" Parameter="maKhoa" Type="System.String" DbType="Char(5)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Diem_HPSelectHK1" Method="Diem_HPSelectHK1">
    <Parameter Name="MaSV" Parameter="maSV" Type="System.String" DbType="Char(15)" />
    <Parameter Name="MaMH" Parameter="maMH" Type="System.String" DbType="Char(5)" />
    <Parameter Name="MaLop" Parameter="maLop" Type="System.String" DbType="Char(5)" />
    <Parameter Name="MaHK" Parameter="maHK" Type="System.String" DbType="Char(10)" />
    <ElementType Name="Diem_HPSelectHK1Result">
      <Column Name="MaSV" Type="System.String" DbType="Char(15)" CanBeNull="true" />
      <Column Name="MaMH" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MaLop" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MaHK" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="DiemKT1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DiemKT2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Diemthi" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Diem_HPSelectMH1" Method="Diem_HPSelectMH1">
    <Parameter Name="MaSV" Parameter="maSV" Type="System.String" DbType="Char(15)" />
    <Parameter Name="MaMH" Parameter="maMH" Type="System.String" DbType="Char(5)" />
    <Parameter Name="MaLop" Parameter="maLop" Type="System.String" DbType="Char(5)" />
    <Parameter Name="MaHK" Parameter="maHK" Type="System.String" DbType="Char(10)" />
    <ElementType Name="Diem_HPSelectMH1Result">
      <Column Name="MaSV" Type="System.String" DbType="Char(15)" CanBeNull="true" />
      <Column Name="MaMH" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MaLop" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MaHK" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="DiemKT1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DiemKT2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Diemthi" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Diem_HPSelectML1" Method="Diem_HPSelectML1">
    <Parameter Name="MaSV" Parameter="maSV" Type="System.String" DbType="Char(15)" />
    <Parameter Name="MaMH" Parameter="maMH" Type="System.String" DbType="Char(5)" />
    <Parameter Name="MaLop" Parameter="maLop" Type="System.String" DbType="Char(5)" />
    <Parameter Name="MaHK" Parameter="maHK" Type="System.String" DbType="Char(10)" />
    <ElementType Name="Diem_HPSelectML1Result">
      <Column Name="MaSV" Type="System.String" DbType="Char(15)" CanBeNull="true" />
      <Column Name="MaMH" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MaLop" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MaHK" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="DiemKT1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DiemKT2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Diemthi" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Diem_HPSelectSV1" Method="Diem_HPSelectSV1">
    <Parameter Name="MaSV" Parameter="maSV" Type="System.String" DbType="Char(15)" />
    <Parameter Name="MaMH" Parameter="maMH" Type="System.String" DbType="Char(5)" />
    <Parameter Name="MaLop" Parameter="maLop" Type="System.String" DbType="Char(5)" />
    <Parameter Name="MaHK" Parameter="maHK" Type="System.String" DbType="Char(10)" />
    <ElementType Name="Diem_HPSelectSV1Result">
      <Column Name="MaSV" Type="System.String" DbType="Char(15)" CanBeNull="true" />
      <Column Name="MaMH" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MaLop" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="MaHK" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="DiemKT1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DiemKT2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Diemthi" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.MonHP_SelectMaHK" Method="MonHP_SelectMaHK">
    <Parameter Name="MaHK" Parameter="maHK" Type="System.String" DbType="Char(10)" />
    <ElementType Name="MonHP_SelectMaHKResult">
      <Column Name="MaMH" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="TenMH" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="SoTC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaHK" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="MaKhoa" Type="System.String" DbType="Char(5)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.BangDiemHP" Method="BangDiemHP">
    <Parameter Name="MaLop" Parameter="maLop" Type="System.String" DbType="Char(5)" />
    <Parameter Name="MaMH" Parameter="maMH" Type="System.String" DbType="Char(5)" />
    <ElementType Name="BangDiemHPResult">
      <Column Name="MaSV" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="TenSV" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DiemKT1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DiemKT2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Diemthi" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DiemHP_Insert" Method="DiemHP_Insert">
    <Parameter Name="MaSV" Parameter="maSV" Type="System.String" DbType="Char(15)" />
    <Parameter Name="MaMH" Parameter="maMH" Type="System.String" DbType="Char(5)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DiemHP_Update" Method="DiemHP_Update">
    <Parameter Name="MaSV" Parameter="maSV" Type="System.String" DbType="Char(15)" />
    <Parameter Name="MaMH" Parameter="maMH" Type="System.String" DbType="Char(5)" />
    <Parameter Name="DiemKT1" Parameter="diemKT1" Type="System.Double" DbType="Float" />
    <Parameter Name="DiemKT2" Parameter="diemKT2" Type="System.Double" DbType="Float" />
    <Parameter Name="Diemthi" Parameter="diemthi" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DiemHP_Search" Method="DiemHP_Search">
    <Parameter Name="MaMH" Parameter="maMH" Type="System.String" DbType="Char(5)" />
    <Parameter Name="MaSV" Parameter="maSV" Type="System.String" DbType="Char(15)" />
    <ElementType Name="DiemHP_SearchResult">
      <Column Name="MaSV" Type="System.String" DbType="Char(15)" CanBeNull="true" />
      <Column Name="MaMH" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="DiemKT1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DiemKT2" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Diemthi" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.MonHP_SelectHK" Method="MonHP_SelectHK">
    <ElementType Name="MonHP_SelectHKResult">
      <Column Name="MaHK" Type="System.String" DbType="Char(10)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>